# Generated by Django 3.0.2 on 2020-03-23 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='User',
            new_name='user',
        ),
    ]
