# Generated by Django 3.0.2 on 2020-03-23 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200323_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.DeleteModel(
            name='Recovery',
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
