# Generated by Django 3.0.2 on 2020-03-23 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200323_2252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Symptoms',
        ),
    ]
