# Generated by Django 3.0.2 on 2020-03-25 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200324_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_name', models.CharField(max_length=100)),
                ('label1', models.CharField(max_length=100)),
                ('label2', models.CharField(max_length=100)),
                ('label3', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('firstname', 'lastname', 'age', 'gender')},
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input1', models.IntegerField()),
                ('input2', models.IntegerField()),
                ('input3', models.IntegerField()),
                ('timestamp', models.TimeField(auto_now_add=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Tracker')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
